[bar]
scale = 0.800000011920929
inset-edge = 0.10000000149011612
inset-ends = 0.550000011920929
padding = 0.4000000059604645
padding-ends = 0.0
bg = "bg-base"
background-opacity = 95
border-location = "all"
border-width = 2
border-color = "bg-overlay"
button-rounding = "sm"
button-gap = 0.25
button-group-rounding = "sm"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "cpu",
    "ram",
    "volume",
    "network",
    "systray",
    "notifications",
]

[styling.palette]
bg = "#0d0a0e"
surface = "#151019"
elevated = "#1e1824"
fg = "#c2b6c0"
fg-muted = "#948a98"
primary = "#bf7593"
red = "#c0667e"
yellow = "#c4a878"
green = "#82a08c"
blue = "#8a7aa6"

[modules.clock]
border-show = true
border-color = "accent"
icon-color = "bg-base"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "bg-base"
dropdown-show-seconds = true

[modules.cpu]
border-show = true
border-color = "accent"
icon-color = "bg-base"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "bg-base"

[modules.dashboard]
border-show = true
border-color = "border-accent"
icon-color = "accent"
icon-bg-color = "bg-base"

[modules.hyprland-workspaces]
min-workspace-count = 3
active-indicator = "underline"
active-color = "accent"
occupied-color = "status-error-hover"
container-bg-color = "bg-base"
border-show = true
border-color = "fg-muted"

[modules.network]
border-show = true
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "bg-base"

[modules.notification]
border-show = true
border-color = "status-info"
icon-color = "bg-base"
icon-bg-color = "status-info"
label-color = "status-info"
button-bg-color = "bg-base"

[modules.ram]
border-show = true
border-color = "accent"
icon-color = "bg-base"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "bg-base"

[modules.systray]
button-bg-color = "bg-base"

[modules.volume]
border-show = true
border-color = "yellow"
icon-bg-color = "yellow"
label-color = "yellow"
button-bg-color = "bg-base"

[modules.weather]
location = "Dijon"

[wallpaper]
engine-enabled = false
transition-type = "none"
cycling-interval-mins = 1440
cycling-same-image = true
