[bar]
scale = 0.800000011920929
inset-edge = 0.10000000149011612
inset-ends = 0.550000011920929
padding = 0.4000000059604645
padding-ends = 0.0
bg = "bg-base"
background-opacity = 95
border-location = "all"
border-width = 2
border-color = "bg-overlay"
button-rounding = "none"
button-gap = 0.25
button-group-rounding = "none"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
]
center = ["clock"]
right = [
    "cpu",
    "ram",
    "volume",
    "network",
    "battery",
    "systray",
    "notifications",
]

[styling.palette]
bg = "#0b0e14"
surface = "#1a1b26"
elevated = "#202230"
fg = "#c0caf5"
fg-muted = "#a9b1d6"
primary = "#ff8f40"
red = "#f7768e"
yellow = "#e0af68"
green = "#9ece6a"
blue = "#7dcfff"

[modules.battery]
border-show = true
border-color = "status-info"
icon-bg-color = "status-info"
label-color = "status-info"
button-bg-color = "bg-base"

[modules.clock]
border-show = true
border-color = "#d2a6ff"
icon-color = "#0b0e14"
icon-bg-color = "#d2a6ff"
label-color = "#d2a6ff"
button-bg-color = "bg-base"
dropdown-show-seconds = true

[modules.cpu]
border-show = true
border-color = "#d2a6ff"
icon-color = "bg-base"
icon-bg-color = "#d2a6ff"
label-color = "#d2a6ff"
button-bg-color = "bg-base"

[modules.dashboard]
border-show = true
border-color = "border-accent"
icon-color = "accent"
icon-bg-color = "bg-base"

[modules.hyprland-workspaces]
min-workspace-count = 3
active-indicator = "underline"
active-color = "#d2a6ff"
occupied-color = "status-error-hover"
container-bg-color = "bg-base"
border-show = true
border-color = "fg-muted"

[modules.network]
border-show = true
border-color = "#d2a6ff"
icon-bg-color = "#d2a6ff"
label-color = "#d2a6ff"
button-bg-color = "bg-base"

[modules.notification]
border-show = true
border-color = "status-info"
icon-color = "bg-base"
icon-bg-color = "status-info"
label-color = "status-info"
button-bg-color = "bg-base"

[modules.ram]
border-show = true
border-color = "accent"
icon-color = "bg-base"
icon-bg-color = "accent"
label-color = "accent"
button-bg-color = "bg-base"

[modules.systray]
button-bg-color = "bg-base"

[modules.volume]
border-show = true
border-color = "yellow"
icon-bg-color = "yellow"
label-color = "yellow"
button-bg-color = "bg-base"

[modules.weather]
location = "Dijon"

[wallpaper]
engine-enabled = false
transition-type = "none"
cycling-interval-mins = 1440
cycling-same-image = true
