# hypridle : verrouillage auto + avant la veille
general {
    lock_cmd = pidof hyprlock || hyprlock                             # un seul hyprlock à la fois
    before_sleep_cmd = loginctl lock-session                          # verrouille avant la veille (capot fermé)
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})' # rallume l'écran au réveil
}

# 5 min sans activité : verrouillage
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5 min 30 : écran éteint (dpms), rallumé au moindre mouvement
listener {
    timeout = 330
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}
